### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [edqx/Hindenburg#4]
### Info
TypeScript Version: 4.2.4
Yarn version: 1.22.4
Node version: 14.3.0
Npm version: 7.6.0
Commit: 58abcf1c021f86b15399cd653e288a2d80c5d5fc
```
src/Room.ts:69:14 - error TS2341: Property '_interval' is private and only acessible within class 'Hostable<T>'.

|69| this._interval = setInterval(
```
### Reproduction Steps
1. git clone this repository
2. Run `yarn install` to install dependencies
3. Run `yarn build` to build server
4. Build fails with error above

**Comment by edqx** [comment]
Hi, sorry for the wait.
Fixed in https://github.com/SkeldJS/SkeldJS/commit/bf635e6bfdc3a8bd8325868b6122d6835e21f637, https://github.com/edqx/Hindenburg/commit/d967aba587977877f4162d198122493447e5882e

**Comment by MacaylaMarvelous81** [comment]
Thanks and no worries :)

**Comment by MacaylaMarvelous81** [comment]
Four more build errors 😞 
### Info
Same versions as previous
Commit: 2963aed6458be819f28ee579806a6da676a9c80b
```ts
src/util/format-player.ts:11:24 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|11| const colour = player.info ? player.info.color : Color.Grey;

src/util/format-player.ts:11:38 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|11| const colour = player.info ? player.info.color : Color.Grey;

src/util/format-player.ts:12:22 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|12| const name = player.info.name || "<No Name>" : "<No Data>";

src/util/format-player.ts:12:36 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|12| const name = player.info.name || "<No Name>" : "<No Data>";
```

**Comment by edqx** [comment]
Run `yarn install` again as `.info` only exists on the new version of SkeldJS that I bumped up in https://github.com/SkeldJS/Hindenburg/commit/7b8e0d769a93565afec237fbf425241a33ae84ff.
